service: myService

provider:
  name: aws
package:
  individually: true
functions:
  function1:
    handler: function1.handler
  function2:
    handler: function2.handler
  function3: 
    handler: function3.handler