name: Build Serverless Backend Lambda Functions

on:
  pull_request:
    branches:
      - dev
      - "hotfix-*"
    paths:
      - "backend/**"
      - "!backend/*.md"
    types:
      - closed
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  getting-lambda-functions-names:
    name: Getting lambda functions names
    defaults:
      run:
        working-directory: ./backend
    if: github.event.pull_request.merged == true || github.event_name == 'release'
    runs-on: ubuntu-latest
    outputs:
      lambda-names: ${{ steps.lambda-names.outputs.names }}
    steps:
      - name: Checkout dev
        if: github.ref == 'refs/heads/dev'
        uses: actions/checkout@v6
        with:
          ref: dev

      - name: Checkout release tag
        if: github.event_name == 'release'
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Checkout hotfix branch
        if: startsWith(github.ref, 'refs/heads/hotfix-')
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Caching npm 
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Grubing functions names
        id: lambda-names
        run: |
          LAMBDA_ARRAY=()
          for f in ./* ; do
            [ -d "$f" ] || continue
            FILE=$(basename "$f")
            NAME="${FILE}"
            LAMBDA_ARRAY+=("\"$NAME\"")
          done
          IFS=,
          JSON="[${LAMBDA_ARRAY[*]}]"
          echo "names=$JSON" >> $GITHUB_OUTPUT
          echo $JSON

  upload-function-s3:
    name: Uploading to S3
    needs: getting-lambda-functions-names
    defaults:
      run:
        working-directory: ./backend    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda: ${{ fromJSON(needs.getting-lambda-functions-names.outputs.lambda-names) }}
    if: github.event.pull_request.merged == true || github.event_name == 'release'
    steps:
      - name: Checkout dev
        if: github.ref == 'refs/heads/dev'
        uses: actions/checkout@v6
        with:
          ref: dev

      - name: Checkout release tag
        if: github.event_name == 'release'
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Checkout hotfix branch
        if: startsWith(github.ref, 'refs/heads/hotfix-')
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Installing node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          

      - name: Installing Infra dependencies
        run: |
          npm install

      - name: Building Lambdas
        run: |
          npx sls package

      - name: Assuming federated role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: Federal

      - name: Assuming worker role (chained)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_WORKER_ROLE_ARN }}
          role-chaining: true
          role-session-name: Secondary

      - name: Deploy Lambda (dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          cd backend/
          aws s3 cp "./.serverless/${{ matrix.lambda }}.zip" s3://${{ secrets.BUCKET_NAME }}/backend/${{ vars.FOLDER_NAME}}/${{ matrix.lambda }}.zip

      - name: Deploy Lambda (release tag)
        if: github.event_name == 'release'
        run: |
          cd backend/lambdas/
          aws s3 cp "./.serverless/${{ matrix.lambda }}.zip" s3://${{ secrets.BUCKET_NAME }}/backend/${{ github.event.release.tag_name }}/${{ matrix.lambda }}.zip

      - name: Deploy Lambda (hotfix)
        if: startsWith(github.ref, 'refs/heads/hotfix-')
        run: |
          cd backend/lambdas/
          aws s3 cp "./.serverless/${{ matrix.lambda }}.zip" s3://${{ secrets.BUCKET_NAME }}/backend/${GITHUB_REF#refs/heads/}/${{ matrix.lambda }}.zip





