name: build-backend

on:
  pull_request:
    branches:
      - dev
      - 'hotfix-*'
    paths:
      - 'backend/**'
      - '!backend/**/*.md'
      
    types:
      - closed
  release:
    types: [created] 

permissions:
  id-token: write
  contents: read

jobs:
  buildLambdas:
    if: github.event.pull_request.merged == true || github.event_name == 'release'
    runs-on: ubuntu-latest
    outputs:
      lambda-names: ${{ steps.get-lambdas.outputs.names }}
    steps:
      - name: Checkout dev
        if: github.ref == 'refs/heads/dev'
        uses: actions/checkout@v6
        with:
          ref: dev

      - name: Checkout release tag
        if: github.event_name == 'release'
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Checkout hotfix branch
        if: startsWith(github.ref, 'refs/heads/hotfix-')
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Infra dependencies
        run: |
          cd backend
          npm install

      - name: Build Lambdas
        run: |
          cd backend
          npx sls package

      - name: Make directory for lambdas
        run: |
          cd backend
          mkdir -p lambdas
          cp ./.serverless/*.zip lambdas/

      - name: Upload Lambda folder
        uses: actions/upload-artifact@v6
        with:
          name: lambda-folder
          path: backend/lambdas/

      - name: Get Lambda names
        id: get-lambdas
        run: |
          cd backend
          LAMBDA_ARRAY=()
          for f in lambdas/*.zip; do
            [ -e "$f" ] || continue
            FILE=$(basename "$f")
            NAME="${FILE%.zip}"
            LAMBDA_ARRAY+=("\"$NAME\"")
          done
          IFS=,
          JSON="[${LAMBDA_ARRAY[*]}]"
          echo "names=$JSON" >> $GITHUB_OUTPUT
          echo $JSON

  LambdaToS3:
    needs: buildLambdas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda: ${{ fromJSON(needs.buildLambdas.outputs.lambda-names) }}
    steps:

      - name: Download Lambda folder
        uses: actions/download-artifact@v4
        with:
          name: lambda-folder
          path: ${{ matrix.lambda }}
      - name: Get Lambda names
        run: |
          ls
      - name: Assume federated role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: Federal

      - name: Assume worker role (chained)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_WORKER_ROLE_ARN }}
          role-chaining: true
          role-session-name: Secondary

      - name: Deploy Lambda (dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          aws s3 cp "${{ matrix.lambda }}.zip" s3://${{ secrets.BUCKET_NAME }}/backend/${{ vars.FOLDER_NAME}}/${{ matrix.lambda }}.zip

      - name: Deploy Lambda (release tag)
        if: github.event_name == 'release'
        run: |

          aws s3 cp "${{ matrix.lambda }}.zip" s3://${{ secrets.BUCKET_NAME }}/backend/${{ github.event.release.tag_name }}/${{ matrix.lambda }}.zip

      - name: Deploy Lambda (hotfix)
        if: startsWith(github.ref, 'refs/heads/hotfix-')
        run: |
          aws s3 cp "${{ matrix.lambda }}.zip" s3://${{ secrets.BUCKET_NAME }}/backend/${GITHUB_REF#refs/heads/}/${{ matrix.lambda }}.zip