name: build-frontend-turborepo-dev

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'frontend/**'
      - '!frontend/**/*.md'
    types:
      - closed
permissions:
  id-token: write
  contents: read

jobs: 
  AppNames:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.get-frontend-apps.outputs.apps  }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install deps
        run: |
          cd frontend
          pnpm install

      - name: Build frontend
        run: |
          cd frontend
          pnpm turbo build

      - name: Get Frontend App Names
        id: get-frontend-apps
        run: |
            cd frontend/apps
            APP_ARRAY=()
            for f in *; do
              [ -e "$f" ] || continue
              APP_ARRAY+=("\"$f\"")
            done
            IFS=,
            JSON="[${APP_ARRAY[*]}]"
            echo "apps=$JSON" >> $GITHUB_OUTPUT
            echo $JSON

      - name: Upload build artifacts (per app)
        run: |
          for app in frontend/apps/*; do
            if [ -d "$app/build" ]; then
              appname=$(basename "$app")
              echo "Uploading $appname"
              gh run upload-artifact \
                --name "frontend-$appname" \
                "$app/build/*"
            fi
          done
        env:
          GH_TOKEN: ${{ github.token }}

  AppToS3:
    needs: AppNames
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJSON(needs.AppNames.outputs.apps) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    

      - name: Download build for app
        uses: actions/download-artifact@v4
        with:
          name: frontend-${{ matrix.app }}
          path: frontend/apps/${{ matrix.app }}/build

      - name: Assume federated role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: Federal

      - name: Assume worker role (chained)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_WORKER_ROLE_ARN }}
          role-chaining: true
          role-session-name: Secondary
      
      - name: Zip builed Apps
        run: |
          cd frontend/apps/${{ matrix.app }}
          zip -r ${{ matrix.app }}.zip build/

      - name: Deploy Apps
        run: |
          cd frontend/apps/${{ matrix.app }}
          aws s3 cp "${{ matrix.app }}.zip" s3://${{ secrets.BUCKET_NAME}}/frontend/${{vars.FOLDER_NAME}}/${{ matrix.app }}.zip
      